### ISSUE TITLE
Unable to Subscribe

### ISSUE THREAD

**Issue by neildsouza** [gausby/gen_mqtt#12]
Hi,

Have been trying (unsuccessfully) to Subscribe to a topic using my GenMQTT Callback module.

``` elixir
defmodule MqttBridge.ConnectionProcess do
    use GenMQTT

    def start_link do
        GenMQTT.start_link(__MODULE__, :ok, [name: __MODULE__])
    end

    def on_connect(state) do
        :ok = GenMQTT.subscribe(self, "Elixir_Test/In", 0)
        {:ok, state}
    end

    def on_connect_error(reason, state) do
        IO.puts reason
        {:ok, state}
    end

    def on_subscribe(list, state) do
        IO.puts list
        {:ok, state}
    end

    def handle_info(msg, state) do
        IO.puts msg
        {:no_reply, state}
    end
end
```

I seem to be getting errors in the on_subscribe callback.

``` elixir
23:34:27.312 [error] ** State machine MqttBridge.ConnectionProcess terminating 
** Last message in was {:tcp, #Port<0.4977>, <<144, 3, 0, 1, 0>>}
** When State == :connected
**      Data  == {:state, 'localhost', 1883, #Port<0.4977>, 2, :undefined, :undefined,
 "455D38CF1A353ACFCEE8", true, :undefined, :undefined, 0, "", :undefined, 60000,
 10000, 3, MqttBridge.ConnectionProcess, :ok, {:gen_tcp, []}, "",
 {:dict, 2, 16, 16, 8, 80, 48,
  {[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []},
  {{[[{:subscribe, 1} |
      {#Reference<0.0.2.226>, {:subscribe, [{"Elixir_Test/In", 0}]}}]], [], [],
    [], [], [], [], [[:ping | #Reference<0.0.2.225>]], [], [], [], [], [], [],
    [], []}}}, {#Function<0.128699311/2 in :gen_emqtt.init/1>, :ok}}
** Reason for termination = 
** {:badarg,
 [{:io, :put_chars, [#PID<0.150.0>, :unicode, [[{"Elixir_Test/In", 0}], 10]],
   []},
  {MqttBridge.ConnectionProcess, :on_subscribe, 2,
   [file: 'lib/mqtt_bridge/connection_process.ex', line: 19]},
  {:gen_emqtt, :wrap_res, 4,
   [file: '/home/neil/programs/elixir_progs/mqtt_bridge/deps/vmq_commons/src/gen_emqtt.erl',
    line: 129]},
  {:gen_emqtt, :process_bytes, 3,
   [file: '/home/neil/programs/elixir_progs/mqtt_bridge/deps/vmq_commons/src/gen_emqtt.erl',
    line: 346]}, {:gen_fsm, :handle_msg, 7, [file: 'gen_fsm.erl', line: 451]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}
```

Any thoughts on whats causing this :(

**Comment by gausby** [comment]
Does it work if you replace IO.puts with IO.inspect ?

**Comment by neildsouza** [comment]
Yesss ... awesome ... Thnx so much.

**Comment by neildsouza** [comment]
Any ideas on how I can handle incoming msgs though.
I thought this would do it ...

``` elixir
def handle_info(msg, state) do
    IO.inspect msg
    {:no_reply, state}
end
```

But nothing gets printed into iex

**Comment by gausby** [comment]
`handle_info/2` is used when another process in the system sends the process a message; `handle_info/2` does not concern itself with what's coming in on the MQTT connection. You can try this by obtaining the pid or the process that runs the GenMQTT behaviour and send it a message with `send pid, "hello"`—in that case you would see `"hello"` getting printed.

I think you are looking for `on_publish/3`, try dropping this into the code and post something to the "Elixir_Test/In" topic on the MQTT server:

``` elixir
def on_publish(["Elixir_Test", "In"], message, state) do
    IO.inspect message
    {:ok, state}
end
```

Does that work?

_edit_ corrected the `send pid, "hello"` example

**Comment by neildsouza** [comment]
Yes ... that works beautifully.
Really sorry for the trouble but I didn't understand what the docs said.

``` elixir
on_publish(topic, payload :: binary, state) :: {:ok, state} when state: term
```

> Callback triggered when a message has been published to a topic the client subscribes to.

Shouldn't that callback be `on_message` instead.
`on_publish` made me think that it would be called if I published something from this handler.

**Comment by gausby** [comment]
Don't be sorry. I am happy that you try out the project :)

That is a valid point. That terminology was confusing to me at first—but this module is really just a wrapper of an Erlang module called vmq_commons, a project filled with various helper functions used by the VerneMQ MQTT broker. This project has a `gen_emqtt` module which implements a MQTT client in Erlang; so—long story short—this is basically a thin wrapper that makes it more convenient to work with `gen_emqtt` in Elixir: The names of the callbacks follow the names used in `gen_emqtt`, where `on_publish/3` is one of them.

I can ask Erlio (the company behind VerneMQ) about the reason for this name—because I am interested myself, now that you mentioned it!

**Comment by neildsouza** [comment]
Completely understand.
Anyways thnx so much again ... for the help and gen_mqtt.
See ya :+1:
