### ISSUE TITLE
gen_mqtt client connect to broker via TLS_v1 PSK sample

### ISSUE THREAD

**Issue by yeongsheng-tan** [gausby/gen_mqtt#13]
@gausby would it be possible to use gen_mqtt to develop a client that connects to a mosquitto broker running on remote port 8883 via TLSv1 psk & psk-identity?

Would appreciate a sample code or pointers towards how to pass that into the connect function via the options map.

**Comment by gausby** [comment]
Hi, as much as I like a challenge I would respectfully ask if you have tried to do it yourself using the examples I have already provided, and the documentation? There are some support for connecting using SSL transports, so perhaps it is possible. Please have a look at the start up options, and the Erlang documentation page it links to on the topic https://github.com/gausby/gen_mqtt/blob/master/lib/gen_mqtt.ex#L335-L396

**Comment by yeongsheng-tan** [comment]
@gausby I'm still not able to get the right config going with the below settings:
`GenMQTT.start_link(host: 'myserver.somewhere.com', port: 8883, transport: {:ssl, [ {:psk_identity, 'myserver'}, {:versions, [:tlsv1]}, {:user_lookup_fun, fun(),term()} ]})`

And I'm getting error as such:
`{:ok, #PID<0.179.0>}
:server_not_found
iex(5)>
18:25:08.407 [error] SSL: :hello: ssl_alert.erl:97:Fatal error: handshake failure`

I saw in the Erlang :ssl documentation, for the use of tls psk auth, `:user_lookup_fun` needs to be defined. I'm not sure how to define this function as an :ssl config param in the start_link function.

My attempt:
```
    fun = fn(psk, psk_identity, user_state) -> {:ok, "my_hardcoded_psk"} end
    user_state = fn -> {:valid, "user_state"} end
    GenMQTT.start_link(__MODULE__, nil, host: "my_mqtt_broker.com", port: 8883, transport: {:ssl, [{:psk_identity, "my_psk_identity"}, {:versions, [:tlsv1]}, {:user_lookup_fun, {fun.("my_hard_coded_psk", "my_psk_identity", user_state), user_state}}]})
```
