### ISSUE TITLE
Subscribing to a list of topics with a global qos does not work

### ISSUE THREAD

**Issue by MichaelBitard** [gausby/gen_mqtt#22]
According to the documentation, this should not work at all, but somehow does not raise any error:
`GenMQTT.subscribe(self(), ["topic1", "topic2"], 1)`

I know that this works:
`GenMQTT.subscribe(self(), [{"topic1", 1}, {"topic2", 1}])`

But I expected to get an error in the first case

**Comment by gausby** [comment]
As I said in a different issue thread. Please look into Tortoise instead, as gen_mqtt has been deprecated: http://github.com/gausby/tortoise/

**Comment by MichaelBitard** [comment]
Thanks!

**Comment by gausby** [comment]
Look into `Tortoise.Handler.Default` and `Tortoise.Handler.Logger`; that is how you implement the callbacks needed when receiving messages, and when topic filters are subscribed to. Notice though that the handler is running in the connection controller, so it is best not the do blocking operations in the handler.

I hope you and your team enjoy using Tortoise, and please let me know if there are any questions or if it doesn't behave. This will help me write the documentation :)
